spring.application.name=Task Manager

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskmanager}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:Q7mN2xLp9Vz4Kf8Rw1Yb6Hs3Cd0Je5TuXa9Pm4GkL8Zn2WqRs7Dv1Fc6Bh3Ty8Ue}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.jpa.open-in-view=false


##flayway elave etmek